def print_help():
    print()
    print("===================================================================")
    print("Telegram Converter (.html-->.txt) v1.0(28.11.2022)")
    print("===================================================================")
    print()
    print("!!! The program is designed to work with Telegram messages !!!")
    print("!!! saved in .html format only! Any other .html file       !!!")
    print("!!! will result in an undefined behavior!                  !!!")
    print()
    print("!!! This program may be outdated at some point due to      !!!")
    print("!!! changes in the file structre made by Telegram!         !!!")
    print()
    print("Usage:")
    print('\t1) Put desired files into the "Input" folder')
    print()
    print("\t2) Use this command in the terminal:")
    print()
    print("\t   python3 tgconverter.py [options]")
    print()
    print('\t3) If everything goes well, check the "Output" folder')
    print()
    print("Options:")
    print('\t"-p" to print files, instead of saving')
    print('\t"-h" to print help... obviously c;')
    print()
    print("===================================================================")
    print("Lemme tell ya, it is so satisfying to design 'help'")
    print()